<?php
/**
 * @file
 * Code for the Events feature.
 */

include_once 'its_events.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function its_events_preprocess_node(&$vars) {
  if ($vars['node']->type == 'event') {
    $node = $vars['node'];
    if ($vars['view_mode'] == 'teaser') {
      $c = '';
      // Date.
      $item = field_get_items('node', $node, 'field_event_date');
      $item = isset($item[0]['value']) ? $item[0]['value'] : NULL;
      if ($item) {
        $date = format_date(strtotime($item), 'event');
        $date = str_replace(
          array(
            'Januaryth',
            'Februaryth',
            'Marchth',
            'Aprilth',
            'Mayth',
            'Juneth',
            'Julyth',
            'Augustth',
            'Septemberth',
            'Octoberth',
            'Novemberth',
            'Decemberth',
          ),
          array(
            t('Januaryth'),
            t('Februaryth'),
            t('Marchth'),
            t('Aprilth'),
            t('Mayth'),
            t('Juneth'),
            t('Julyth'),
            t('Augustth'),
            t('Septemberth'),
            t('Octoberth'),
            t('Novemberth'),
            t('Decemberth'),
          ),
          $date
        );
        $date = str_replace('th ', ' ', $date);
        $c .= '<span class="event-date">' . $date . '</span>';
      }

      // Title.
      $c .= '<span class="event-title">' . $node->title . '</span>';

      // Body.
      $body = field_get_items('node', $node, 'body');
      $item = isset($body[0]['summary']) ? $body[0]['summary'] : '';
      if (!$item) {
        $item = isset($body[0]['safe_value']) ? $body[0]['safe_value'] : '';
      }
      if ($item) {
        $alter = array(
          'max_length' => 130,
          'ellipsis' => TRUE,
          'word_boundary' => TRUE,
          'html' => TRUE,
        );
        $c .= '<span class="event-body">' . views_trim_text($alter, $item) . '</span>';
      }

      // Link.
      $c .= '<span class="event-link">' . t('Read More') . '</span>';

      // Image.
      $item = field_get_items('node', $node, 'field_event_image');
      $item = isset($item[0]['uri']) ? $item[0]['uri'] : NULL;
      $style = array();
      if ($item) {
        $item = image_style_url('upcoming_events', $item);
        $style = array('background-image:url(' . $item . ');');
      }
      // Add triangles.
      $c = '<span class="event-triangle-top"></span>' . $c;
      $c .= '<span class="event-triangle-bottom"></span>';
      $vars['event_element'] = l(
        $c,
        'node/' . $node->nid,
        array(
          'html' => TRUE,
          'attributes' => array(
            'class' => array('event-link-wrapper'),
            'style' => $style,
          ),
        )
      );
    }
  }
}
