<?php

/**
 * @file
 * ITS Social module.
 */

/**
 * Implements hook_theme().
 */
function its_social_theme($existing, $type, $theme, $path) {
  return array(
    'its_social_links' => array(
      'variables' => array(
        'links' => array(),
      ),
      'file' => 'its_social.theme.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function its_social_block_info() {
  $blocks['its_social_links'] = array(
    'info' => t('ITS Social Links'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function its_social_block_view($delta = '') {
  global $language;
  $block = array();

  switch ($delta) {
    case 'its_social_links':
      $block['subject'] = '';
      $links = array();
      $tid = its_cities_get_current_city();
      $q = db_select('node', 'n');
      $q->join('field_data_field_city', 'c', 'n.nid = c.entity_id');

      $q->fields('n', array('nid'))
        ->condition('n.type', 'phones')
        ->condition('n.status', NODE_PUBLISHED)
        ->condition('n.language', $language->language)
        ->condition('c.field_city_tid', $tid);
      $nid = $q->execute()
        ->fetchField();
      $node = node_load($nid);
      if ($node) {
        $fields = array(
          'facebook',
          'instagram',
          'youtube',
          'googleplus',
        );
        foreach ($fields as $name) {
          $item = field_get_items('node', $node, "field_{$name}");
          $url = isset($item[0]['url']) ? $item[0]['url'] : NULL;
          if ($url) {
            $links[$name] = array(
              'text' => $item[0]['title'],
              'path' => $url,
            );
          }
        }
      }
      $block['content'] = theme('its_social_links', array('links' => $links));
      break;

  }
  return $block;
}
