<?php
/**
 * @file
 * Code for the ITS Class feature.
 */

include_once 'its_class.features.inc';

/**
 * Implements hook_preprocess_views_view().
 */
function its_class_preprocess_views_bootstrap_table_plugin_style(&$vars) {
  $view = $vars['view'];
  if ($view->name == 'its_subject') {
    switch ($view->current_display) {
      case 'panel_pane_full_package':
      case 'attachment_custom_package':
        $vars['total'] = 0;
        foreach ($view->result as $key => $result) {
          $vars['total'] += $result->field_field_subject_price[0]['raw']['amount'];
          $vars['field_attributes']['field_subject_price'][$key] = array(
            'data-price' => $vars['total'] / 100,
          );
        }
        $vars['total_formated'] = commerce_currency_format($vars['total'], 'UAH');
        $vars['four_price'] = commerce_currency_format($vars['total'] / 4, 'UAH');
        break;

      default:
        # code...
        break;
    }
  }
}
